/*
=============================================================
Business Analysis
=============================================================
Project : Customer Churn Analysis using PostgreSQL
Author  : Soumyadip Sinha Roy
Purpose : Analyze customer demographics, services, revenue,
          payment behavior, and churn patterns to generate
          business insights using SQL.
=============================================================
*/

--==============================
-- SECTION 1: DATABASE OVERVIEW 
--==============================

-- Q1: Count the total number of customers in the dataset.
SELECT COUNT(*) AS total_customers
FROM customers;

-- Q2: Count customers by churn status.
SELECT churn, COUNT(*) AS customer_count
FROM customers
GROUP BY churn
ORDER BY customer_count DESC;

-- Q3: Count customers by gender.
SELECT gender, COUNT(*) AS customer_count
FROM customers
GROUP BY gender
ORDER BY customer_count DESC;

-- Q4: Count customers by contract type.
SELECT contract, COUNT(*) AS customer_count
FROM customers
GROUP BY contract
ORDER BY customer_count DESC;

-- Q5: Count customers by internet service type.
SELECT internet_service, COUNT(*) AS customer_count
FROM customers
GROUP BY internet_service
ORDER BY customer_count DESC;

-- Q6: Count customers by payment method.
SELECT payment_method, COUNT(*) AS customer_count
FROM customers
GROUP BY payment_method
ORDER BY customer_count DESC;

-- Q7: Calculate the average customer tenure.
SELECT ROUND(AVG(tenure), 2) AS average_tenure_months
FROM customers;

-- Q8: Calculate the total monthly revenue generated by all customers.
SELECT ROUND(SUM(monthly_charges), 2) AS total_monthly_revenue
FROM customers;

-- Q9: Calculate the total lifetime revenue from all customers.
SELECT ROUND(SUM(total_charges), 2) AS total_lifetime_revenue
FROM customers;

-- Q10: Calculate the average monthly charges per customer.
SELECT ROUND(AVG(monthly_charges), 2) AS average_monthly_charges
FROM customers;

-- Q11: Calculate the average lifetime charges per customer.
SELECT ROUND(AVG(total_charges), 2) AS average_lifetime_charges
FROM customers;

--===================================
-- SECTION 2: CUSTOMER CHURN ANALYSIS
--===================================

-- Q12: Compare the average tenure of churned and retained customers.
SELECT churn, ROUND(AVG(tenure),2) AS average_tenure_months
FROM customers
GROUP BY churn
ORDER BY average_tenure_months DESC;

-- Q13: Compare the average monthly charges of churned and retained customers.
SELECT churn, ROUND(AVG(monthly_charges),2) AS average_monthly_charges
FROM customers
GROUP BY churn
ORDER BY average_monthly_charges DESC;

-- Q14: Compare the average lifetime charges of churned and retained customers.
SELECT churn, ROUND(AVG(total_charges), 2) AS average_lifetime_charges
FROM customers
GROUP BY churn
ORDER BY average_lifetime_charges DESC;

-- Q15: Calculate the churn rate by gender.
SELECT gender, COUNT(*) AS total_customers,
		SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
		ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2)
		AS churn_rate_percentage
FROM customers
GROUP BY gender
ORDER BY churn_rate_percentage DESC;

-- Q16: Calculate the churn rate by senior citizen status.
SELECT senior_citizen, COUNT(*) AS total_customers,
		SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
		ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2)
		AS churn_rate_percentage
FROM customers
GROUP BY senior_citizen
ORDER BY churn_rate_percentage DESC;

-- Q17: Calculate the churn rate by partner status.
SELECT partner, COUNT(*) AS total_customers,
		SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
		ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2)
		AS churn_rate_percentage
FROM customers
GROUP BY partner
ORDER BY churn_rate_percentage DESC;

-- Q18: Calculate the churn rate by dependent status.
SELECT dependents, COUNT(*) AS total_customers,
		SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
		ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2)
		AS churn_rate_percentage
FROM customers
GROUP BY dependents
ORDER BY churn_rate_percentage DESC;

-- Q19: Calculate the churn rate by contract type.
SELECT contract, COUNT(*) AS total_customers,
       SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
       ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2)
	   AS churn_rate_percentage
FROM customers
GROUP BY contract
ORDER BY churn_rate_percentage DESC;

-- Q20: Calculate the churn rate by internet service type.
SELECT internet_service, COUNT(*) AS total_customers,
       SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
       ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2)
	   AS churn_rate_percentage
FROM customers
GROUP BY internet_service
ORDER BY churn_rate_percentage DESC;

-- Q21: Calculate the churn rate by payment method.
SELECT payment_method, COUNT(*) AS total_customers,
       SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
       ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2)
	   AS churn_rate_percentage
FROM customers
GROUP BY payment_method
ORDER BY churn_rate_percentage DESC;

-- Q22: Calculate the churn rate by paperless billing status.
SELECT paperless_billing, COUNT(*) AS total_customers,
       SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
       ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2)
	   AS churn_rate_percentage
FROM customers
GROUP BY paperless_billing
ORDER BY churn_rate_percentage DESC;

-- Q23: Calculate the churn rate by phone service.
SELECT phone_service, COUNT(*) AS total_customers,
       SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
       ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2)
	   AS churn_rate_percentage
FROM customers
GROUP BY phone_service
ORDER BY churn_rate_percentage DESC;

-- Q24: Calculate the churn rate by multiple lines service.
SELECT multiple_lines, COUNT(*) AS total_customers,
       SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
       ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2)
	   AS churn_rate_percentage
FROM customers
GROUP BY multiple_lines
ORDER BY churn_rate_percentage DESC;

-- Q25: Calculate the churn rate by online security service.
SELECT online_security, COUNT(*) AS total_customers,
       SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
       ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2)
	   AS churn_rate_percentage
FROM customers
GROUP BY online_security
ORDER BY churn_rate_percentage DESC;

-- Q26: Calculate the churn rate by online backup service.
SELECT online_backup,COUNT(*) AS total_customers,
       SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
       ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2)
	   AS churn_rate_percentage
FROM customers
GROUP BY online_backup
ORDER BY churn_rate_percentage DESC;

-- Q27: Calculate the churn rate by device protection service.
SELECT device_protection, COUNT(*) AS total_customers,
       SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
       ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2)
	   AS churn_rate_percentage
FROM customers
GROUP BY device_protection
ORDER BY churn_rate_percentage DESC;

-- Q28: Calculate the churn rate by tech support service.
SELECT tech_support, COUNT(*) AS total_customers,
       SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
       ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2)
	   AS churn_rate_percentage
FROM customers
GROUP BY tech_support
ORDER BY churn_rate_percentage DESC;

-- Q29: Calculate the churn rate by streaming TV service.
SELECT streaming_tv, COUNT(*) AS total_customers,
       SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
       ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2)
	   AS churn_rate_percentage
FROM customers
GROUP BY streaming_tv
ORDER BY churn_rate_percentage DESC;

-- Q30: Calculate the churn rate by streaming movies service.
SELECT streaming_movies, COUNT(*) AS total_customers,
       SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
       ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2)
	   AS churn_rate_percentage
FROM customers
GROUP BY streaming_movies
ORDER BY churn_rate_percentage DESC;

--=======================================
-- SECTION 3: CONTRACT & PAYMENT ANALYSIS
--=======================================

-- Q31: Compare the average customer tenure by contract type.
SELECT contract, ROUND(AVG(tenure), 2) AS average_tenure_months
FROM customers
GROUP BY contract
ORDER BY average_tenure_months DESC;

-- Q32: Compare the average monthly charges by contract type.
SELECT contract, ROUND(AVG(monthly_charges), 2) AS average_monthly_charges
FROM customers
GROUP BY contract
ORDER BY average_monthly_charges DESC;

-- Q33: Compare the average lifetime charges by contract type.
SELECT contract, ROUND(AVG(total_charges), 2) AS average_lifetime_charges
FROM customers
GROUP BY contract
ORDER BY average_lifetime_charges DESC;

-- Q34: Compare the average monthly charges by payment method.
SELECT payment_method, ROUND(AVG(monthly_charges), 2) AS average_monthly_charges
FROM customers
GROUP BY payment_method
ORDER BY average_monthly_charges DESC;

-- Q35: Compare the average lifetime charges by payment method.
SELECT payment_method, ROUND(AVG(total_charges), 2) AS average_lifetime_charges
FROM customers
GROUP BY payment_method
ORDER BY average_lifetime_charges DESC;

--============================
-- SECTION 4: REVENUE ANALYSIS
--============================

-- Q36: Calculate the total lifetime revenue generated by each contract type.
SELECT contract, ROUND(SUM(total_charges), 2) AS total_lifetime_revenue
FROM customers
GROUP BY contract
ORDER BY total_lifetime_revenue DESC;

-- Q37: Calculate the total lifetime revenue generated by each internet service type.
SELECT internet_service, ROUND(SUM(total_charges), 2) AS total_lifetime_revenue
FROM customers
GROUP BY internet_service
ORDER BY total_lifetime_revenue DESC;

-- Q38: Calculate the total lifetime revenue generated by each payment method.
SELECT payment_method, ROUND(SUM(total_charges), 2) AS total_lifetime_revenue
FROM customers
GROUP BY payment_method
ORDER BY total_lifetime_revenue DESC;

-- Q39: Estimate the total lifetime revenue lost due to customer churn.
SELECT ROUND(SUM(total_charges), 2) AS estimated_revenue_lost
FROM customers
WHERE churn = 'Yes';

-- Q40: Identify the highest revenue-generating customer segment by contract type.
SELECT contract, COUNT(*) AS total_customers,
       ROUND(SUM(total_charges), 2) AS total_lifetime_revenue
FROM customers
GROUP BY contract
ORDER BY total_lifetime_revenue DESC;

--=================================
-- SECTION 5: ADVANCED SQL ANALYSIS
--=================================

-- Q41: Categorize customers into tenure groups using CASE.
SELECT CASE WHEN tenure < 12 THEN '0-11 Months'
			WHEN tenure BETWEEN 12 AND 23 THEN '12-23 Months'
			WHEN tenure BETWEEN 24 AND 47 THEN '24-47 Months'
			WHEN tenure BETWEEN 48 AND 71 THEN '48-71 Months'
			ELSE '72+ Months' END AS tenure_group,
			COUNT(*) AS total_customers
FROM customers
GROUP BY tenure_group
ORDER BY total_customers DESC;

-- Q42: Calculate the churn rate by tenure group.
SELECT CASE WHEN tenure < 12 THEN '0-11 Months'
			WHEN tenure BETWEEN 12 AND 23 THEN '12-23 Months'
			WHEN tenure BETWEEN 24 AND 47 THEN '24-47 Months'
			WHEN tenure BETWEEN 48 AND 71 THEN '48-71 Months'
			ELSE '72+ Months' END AS tenure_group,
			COUNT(*) AS total_customers,
			SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
			ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2)
			AS churn_rate_percentage
FROM customers
GROUP BY tenure_group
ORDER BY churn_rate_percentage DESC;

-- Q43: Categorize customers into monthly charge groups using CASE.
SELECT CASE WHEN monthly_charges < 35 THEN 'Low'
			WHEN monthly_charges BETWEEN 35 AND 69.99 THEN 'Medium'
			WHEN monthly_charges BETWEEN 70 AND 99.99 THEN 'High'
			ELSE 'Very High' END AS monthly_charge_group,
			COUNT(*) AS total_customers
FROM customers
GROUP BY monthly_charge_group
ORDER BY total_customers DESC;

-- Q44: Calculate the churn rate by monthly charge group.
SELECT CASE WHEN monthly_charges < 35 THEN 'Low'
			WHEN monthly_charges BETWEEN 35 AND 69.99 THEN 'Medium'
			WHEN monthly_charges BETWEEN 70 AND 99.99 THEN 'High'
			ELSE 'Very High' END AS monthly_charge_group,
			COUNT(*) AS total_customers,
			SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
			ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2)
			AS churn_rate_percentage
FROM customers
GROUP BY monthly_charge_group
ORDER BY churn_rate_percentage DESC;

-- Q45: Rank contract types by churn rate using RANK().
WITH contract_churn AS (
		SELECT contract, COUNT(*) AS total_customers,
		SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
		ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2)
		AS churn_rate_percentage
    FROM customers
    GROUP BY contract)
SELECT contract, total_customers, churned_customers, churn_rate_percentage,
	RANK() OVER (ORDER BY churn_rate_percentage DESC) AS churn_rank
FROM contract_churn;

-- Q46: Rank payment methods by average monthly charges using DENSE_RANK().
SELECT payment_method, ROUND(AVG(monthly_charges), 2) AS average_monthly_charges,
		DENSE_RANK() OVER (ORDER BY AVG(monthly_charges) DESC) AS charge_rank
FROM customers
GROUP BY payment_method;

-- Q47: Divide customers into monthly charge quartiles using NTILE().

/* Use NTILE() to segment customers into quartiles, making it
easier to compare customer groups based on their monthly
spending patterns. */

SELECT customer_id, monthly_charges,
      NTILE(4) OVER (ORDER BY monthly_charges) AS charge_quartile
FROM customers
ORDER BY monthly_charges;

-- Q48: Identify the top 10 customers by lifetime revenue using ROW_NUMBER().
SELECT customer_id, total_charges,
		ROW_NUMBER() OVER (ORDER BY total_charges DESC) AS revenue_rank
FROM customers
WHERE total_charges IS NOT NULL
ORDER BY total_charges DESC
LIMIT 10;

-- Q49: Identify customer segments with the highest churn rate using a CTE.
WITH contract_churn AS (
		SELECT contract, COUNT(*) AS total_customers,
		SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
		ROUND(100.0 * SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2)
		AS churn_rate_percentage
	FROM customers
    GROUP BY contract)
SELECT contract, total_customers, churned_customers, churn_rate_percentage
FROM contract_churn
ORDER BY churn_rate_percentage DESC;

-- Q50: Generate a customer summary report using a CTE and CASE.
WITH customer_summary AS (
		SELECT CASE WHEN tenure < 12 THEN '0-11 Months'
					WHEN tenure BETWEEN 12 AND 23 THEN '12-23 Months'
					WHEN tenure BETWEEN 24 AND 47 THEN '24-47 Months'
					WHEN tenure BETWEEN 48 AND 71 THEN '48-71 Months'
					ELSE '72+ Months' END AS tenure_group, churn,
					COUNT(*) AS total_customers,
					ROUND(AVG(monthly_charges), 2) AS average_monthly_charges,
					ROUND(AVG(total_charges), 2) AS average_lifetime_charges
		FROM customers
		GROUP BY
		CASE 	WHEN tenure < 12 THEN '0-11 Months'
				WHEN tenure BETWEEN 12 AND 23 THEN '12-23 Months'
				WHEN tenure BETWEEN 24 AND 47 THEN '24-47 Months'
				WHEN tenure BETWEEN 48 AND 71 THEN '48-71 Months'
				ELSE '72+ Months' END, churn)
SELECT * FROM customer_summary
ORDER BY tenure_group, churn;